# Generated by Django 2.2.5 on 2019-11-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Photo title', max_length=100)),
                ('description', models.TextField(help_text='Photo description', max_length=1000)),
                ('path', models.FilePathField(path='home/images/slider/')),
            ],
        ),
    ]
