# Generated by Django 2.2.5 on 2019-11-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderPhoto',
            new_name='SliderPhotos',
        ),
    ]
