# Generated by Django 2.2.5 on 2019-11-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191106_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderPhotos',
            new_name='SliderPhoto',
        ),
    ]
