# Generated by Django 2.2.5 on 2019-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191106_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderphoto',
            name='path',
            field=models.FilePathField(),
        ),
    ]
