# Generated by Django 2.2.5 on 2019-11-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191108_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderphoto',
            name='path',
            field=models.CharField(help_text='Path to image source (relative, for static)', max_length=50),
        ),
    ]
