# Generated by Django 2.2.5 on 2019-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191111_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Photo title', max_length=100)),
                ('description', models.TextField(help_text='Photo description', max_length=1000)),
                ('path', models.CharField(help_text='Path to image source (relative, for static)', max_length=50)),
                ('genre', models.CharField(help_text='Image genre (landscape, cityscape, ...)', max_length=15)),
            ],
        ),
    ]
