# Generated by Django 2.2.5 on 2019-11-12 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_galleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='path_original',
            field=models.CharField(default=django.utils.timezone.now, help_text='Path to the original image source (in static dir)', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='description',
            field=models.TextField(help_text='Photo description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='path',
            field=models.CharField(help_text='Path to the resized image source (in for static)', max_length=50),
        ),
    ]
