# Generated by Django 2.2.5 on 2020-01-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191112_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='location',
            field=models.CharField(help_text='Location (coordinates or location name)', max_length=80, null=True),
        ),
    ]
